version: 2
project_name: nsxt_exporter
builds:
  - id: binary
    dir: .
    main: ./main.go
    binary: nsxt_exporter
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser={{.Env.USER}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X code.cloudfoundry.org/cli/version/binaryVersion={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - id: archives
    ids: [binary]
    formats: ['tar.gz']
    name_template: '{{ .ProjectName }}_{{ .Version }}.{{ .Os }}-{{ .Arch }}'
    wrap_in_directory: true
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        formats: ['zip']
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - 'docs'
    - '\.md'
checksum:
  name_template: checksums.txt
  algorithm: sha256
dockers_v2:
  - ids: [binary]
    images:
      - "orangeopensource/nsxt-exporter"
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
    platforms:
      - linux/amd64
    labels:
      "org.opencontainers.image.description": "NSX-T Prometheus Exporter"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    sbom: false
release:
  prerelease: auto
  name_template: '{{.Tag}}'
