name: stale-issue-pr

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Comment or this will be closed in 5 days.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Comment or this will be closed in 5 days.'
          close-issue-message: 'This issue was automatically closed because it has been stalled for 5 days with no activity.'
          close-pr-message: 'This PR was automatically closed because it has been stalled for 5 days with no activity.'
          days-before-stale: 60
          days-before-close: 5
          exempt-all-pr-assignees: true
          operations-per-run: 60
