name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21"

      - name: running unit-tests
        run: |
          go test -v ./...
